### PR TITLE
Data visitor

### LINKED ISSUE #94: Query error for property with large String
I saved large string in database but when try to make query to get it I get error:
```
E/flutter (31707): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: ObjectBoxException: find: 10098 Do not use vector-based find on 32 bit systems with big objects
E/flutter (31707): #0      checkObxPtr (package:objectbox/src/bindings/helpers.dart:15:5)
E/flutter (31707): #1      Query.find.<anonymous closure> (package:objectbox/src/query/query.dart:574:26)
E/flutter (31707): #2      Store.runInTransaction (package:objectbox/src/store.dart:69:16)
E/flutter (31707): #3      Query.find (package:objectbox/src/query/query.dart:573:19)
```
This problem is only for x86 Android Emulator and it is ok for physical devices.
I founded very similar issue for Java Objectbox that was fixed 1 year ago - [java issue](https://github.com/objectbox/objectbox-java/issues/669)

Thanks!

### PR DESCRIPTION
**Pull request by vaind**
Fixes #94

### CODE REVIEW

File: lib/src/bindings/data_visitor.dart [hunk 1]
```diff
@@ -0,0 +1,50 @@
+import 'dart:ffi';
+import 'signatures.dart';
+import "package:ffi/ffi.dart" show allocate, free;
+
+int _lastId = 0;
+final _callbacks = <int, bool Function(Pointer<Uint8> dataPtr, int length)>{};
```
Comment (greenrobot) [inline lib/src/bindings/data_visitor.dart]: What do we need that for? E.g. this is one of the visitor C APIs:

obx_err obx_query_visit(OBX_query* query, obx_data_visitor* visitor, void* user_data, uint64_t offset, uint64_t limit);

I assume you want to pass "id" as `user_data`? Is this more "convenient" that passing in a lambda-like thingy as `visitor`? The latter would already be thread-safe, which the current map-based is not, I think?

File: lib/src/box.dart [hunk 2]
```diff
@@ -160,34 +162,63 @@ class Box<T> {
...
     return _store.runInTransaction(TxMode.Read, () {
-      final bytesArray = cCall();
+      if (_supportsBytesArrays) {
+        final bytesArray = cGetArray();
+        try {
+          return _fbManager.unmarshalArray(bytesArray, allowMissing: allowMissing);
+        } finally {
+          bindings.obx_bytes_array_free(bytesArray);
+        }
+      }
```
Comment (greenrobot) [inline lib/src/box.dart]: Can we have an `} else {` here to better mark the two approaches?

File: lib/src/bindings/data_visitor.dart (hunk 1 above)
Comment (vaind) [reply lib/src/bindings/data_visitor.dart]: Lambdas can't be passed as a C callback, FFI requires static functions. I've tried that (lambda) approach but had to resolve to this trampoline one instead (basically the same thing we do in Go)

File: lib/src/box.dart (hunk 2 above)
Comment (vaind) [reply lib/src/box.dart]: sure

File: lib/src/bindings/data_visitor.dart (hunk 1 above)
Comment (greenrobot) [reply lib/src/bindings/data_visitor.dart]: Sure, please make sure to document that in the code so that this explanation is not lost

Comment (greenrobot) [reply lib/src/bindings/data_visitor.dart]: > The latter would already be thread-safe, which the current map-based is not, I think?

I think this was not addressed yet. Does that require additional thread synchronization?

Comment (vaind) [reply lib/src/bindings/data_visitor.dart]: There is no concurrent memory access in Dart. All code in a single isolate executes on a single event-loop and isolates don't share memory.

Comment (greenrobot) [reply lib/src/bindings/data_visitor.dart]: Interesting concept. Didn't dig into into, but still have a question. We don't have just Dart but also native code. What happens when you [spawn](https://api.dart.dev/stable/2.7.1/dart-isolate/Isolate/spawn.html) a new isolate / event loop? And call into our native library?

Comment (vaind) [reply lib/src/bindings/data_visitor.dart]: Haven't tried that yet and I think it's just like threads in any other language (except you can't share variables inside dart). 

And yes tests like that make sense. We had an issue regarding isolates so I kinda related stuff like this to that issue, in my head. writing it down now #52

Comment (greenrobot) [reply lib/src/bindings/data_visitor.dart]: If isolates behave like threads and vars like thread-locals, this would be a bug, agreed?

Comment (vaind) [reply lib/src/bindings/data_visitor.dart]: how so? I don't see a problem

Comment (greenrobot) [reply lib/src/bindings/data_visitor.dart]: To my limited understanding, I imagine this to happen:
- Let's assume two isolates, both starting with IDs at 1 (produce colliding IDs, because isolated...)
- Callbacks from core happen on a different thread
- (Open question: not sure about how a "foreign" thread is mapped to an isolate. So, which isolate gets the callback?)
- Now, I don't see how we ensured that one isolate gets **only its callback in using its ID**.

E.g. Isolate 2 registers a callback for ID 1, but isolate 1 gets to consume it because it also has a pending callback for ID 1.

Comment (vaind) [reply lib/src/bindings/data_visitor.dart]: > Callbacks from core happen on a different thread

They don't with objectbox-c - all calls are synchronous, executed on the same thread. This approach wouldn't work for other kinds of callbacks, where you register the callback and it may happen in the future (e.g. some kind of event listeners). Not sure how that could be handled with dart, if at all.

Comment (vaind) [reply lib/src/bindings/data_visitor.dart]: Looks like it's an open issue with some workarounds available https://github.com/dart-lang/sdk/issues/37022

Comment (greenrobot) [reply lib/src/bindings/data_visitor.dart]: Right, that one is strictly synchronous and if FFI guarantees synchronous callbacks to execute in the same isolate (I assume that is defined somewhere?), we should be fine.
